apiVersion: v2
name: qdrant-operator
description: Kubernetes operator for managing Qdrant vector database clusters
type: application
version: 0.2.0
appVersion: 0.2.0
kubeVersion: '>=1.26.0'
home: https://github.com/4thel00z/qdrant-operator
icon: >-
  https://raw.githubusercontent.com/4thel00z/qdrant-operator/main/assets/logo.svg
sources:
  - https://github.com/4thel00z/qdrant-operator
